import { Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "AI for Good Hackathon 2026",
    company: "Devpost",
    type: "hackathon",
    deadline: "2026-03-15T23:59:00Z",
    description: "Build AI solutions addressing social challenges. Open to all skill levels. Prizes worth $50,000.",
    skills: ["Python", "Machine Learning", "TensorFlow", "NLP"],
    url: "https://devpost.com",
    isLatest: true,
  },
  {
    id: "2",
    title: "Software Engineering Intern",
    company: "Stripe",
    type: "internship",
    deadline: "2026-03-01T23:59:00Z",
    description: "Join Stripe's payments infrastructure team. Work on distributed systems serving millions of API requests.",
    skills: ["TypeScript", "Go", "Distributed Systems", "APIs"],
    url: "https://stripe.com/jobs",
    isLatest: true,
  },
  {
    id: "3",
    title: "MLH Global Hack Week",
    company: "MLH",
    type: "hackathon",
    deadline: "2026-02-28T23:59:00Z",
    description: "Week-long hacking event with daily challenges, workshops, and mini-hackathons.",
    skills: ["Any Language", "Web Dev", "Mobile", "Data Science"],
    url: "https://mlh.io",
    isLatest: true,
  },
  {
    id: "4",
    title: "Full-Stack Developer",
    company: "Vercel",
    type: "job",
    deadline: "2026-04-01T23:59:00Z",
    description: "Build the future of web deployment. Work with Next.js, Edge Functions, and serverless infrastructure.",
    skills: ["React", "Next.js", "TypeScript", "Node.js"],
    url: "https://vercel.com/careers",
  },
  {
    id: "5",
    title: "Data Science Intern",
    company: "Spotify",
    type: "internship",
    deadline: "2026-03-20T23:59:00Z",
    description: "Work on recommendation algorithms and audio ML models powering 600M+ users.",
    skills: ["Python", "SQL", "Machine Learning", "Statistics"],
    url: "https://lifeatspotify.com",
  },
  {
    id: "6",
    title: "Unstop Innovation Challenge",
    company: "Unstop",
    type: "hackathon",
    deadline: "2026-03-10T23:59:00Z",
    description: "India's largest innovation challenge. Build solutions for real-world industry problems.",
    skills: ["Problem Solving", "Full Stack", "Cloud", "AI/ML"],
    url: "https://unstop.com",
    isLatest: true,
  },
];
